config/routes.rb
Rails.application.routes.draw do
  root 'home#splash'

  get 'home/index'
  get 'math/report'
  post 'math/report'

  get 'math/report2'
  post 'math/report2'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/math' => 'math#start'
  get '/math/select' => 'math#select'
  post '/math/select' => 'math#select'
  get '/math/solve' => 'math#solve'
  post '/math/solve' => 'math#solve'
  # solve2
  get '/math/solve2' => 'math#solve2'
  post '/math/solve2' => 'math#solve2'
  post '/math/grade' => 'math#grade'

  get 'math/explain'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/explain.rb
class Explain < ApplicationRecord
  belongs_to :quest
end

app/models/quest.rb
class Quest < ApplicationRecord
  serialize :info, Hash
  # serialize :content, Array
  has_many :explain
  # Uquest
  has_many :uquests
  has_many :users, through: :uquests


  # def self.next_quest(user,cnt)
  #   resultAry = []
  #   Quest.where(id: Uquest.fail_ary(user,cnt)).each do |q|
  #     resultAry.push(q.info)
  #   end
  # end
  # def self.searchU(user_level_unit)
  #   quests = []
  #   user_level_unit.keys.zip(user_level_unit.values).each do |u, l|
  #     for i in 1..Quest.all.length
  #       quest_info = Quest.find(i).info
  #       quest_info.keys.zip(quest_info.values).each do |k, v|
  #       for j in 0..(u.length - 1)
  #         for h in 0..(k.length - 1)
  #             if u[j] == k[h] && l[j] == v[h]
  #                quests.push(Quest.find(i).id)
  #             end
  #           end
  #         end
  #       end
  #     end
  #   end
  #
  #   return quests
  # end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :units
end

app/models/ulevel.rb
class Ulevel < ApplicationRecord
  belongs_to :user
  belongs_to :unit
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :subject
  # quest 관계 모델
  has_many :quests
  # user 관계 모델
  has_many :ulevels
  has_many :users, through: :ulevels
end

app/models/uquest.rb
class Uquest < ApplicationRecord
  belongs_to :user
  belongs_to :quest

  def self.fail_ary(user,cnt)
    resultAry=[]
    self.where(user_id: user.id, cnt: cnt).each do |uq|
      resultAry.push(uq.quest_id) unless uq.correct
    end
    return resultAry
  end


end

app/models/user.rb
class User < ApplicationRecord
  # ulevel 모델 관계
  has_many :ulevels
  has_many :units, through: :ulevels
  # uquest 모델 관계
  has_many :uquests
  has_many :quests, through: :uquests
  # 로그인 부분
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include MathHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def splash
  end

  def index
  end
end

app/controllers/math_controller.rb
class MathController < ApplicationController
    def report
      @quest = Quest.find(5)
      grade(params[:answer], @quest)
      @fdata=get_report(current_user,current_user.cnt,1)
      @sdata=get_report(current_user,current_user.cnt,2)
    end
    def report2
      @quest = Quest.find(10)
      grade(params[:answer], @quest)
      @fdata=get_report(current_user,current_user.cnt,1)
      @sdata=get_report(current_user,current_user.cnt,2)
      render 'report'
    end
    def start
      @subjects_su2 = Subject.where(big: "수학 Ⅱ")
      @subjects_der = Subject.where(big: "미적분 Ⅰ")
    end

    def select
      # subjects = params[:subject_ids]
      #
      # units_id=[]
      # user_level_unit = Hash.new
      #
      # Unit.where(subject_id: subjects).each do |u|
      #   units_id.push(u.id)
      # end
      #
      # Ulevel.where(unit_id: units_id, user_id: 1).each do |l|
      #   user_level_unit["#{l.unit_id}"] = l.level  #current_user id 추가도 해야 됨
      # end
      #
      # quests = Quest.searchU(user_level_unit)
      # puts quests
      # session[:final_quest_id] ||= quests

      cnt2=current_user.cnt+1
      current_user.update!(cnt: cnt2)

      if current_user.cnt.even? && current_user.cnt!=0
        redirect_to math_solve2_path(:id => 6)
      else
        redirect_to math_solve_path(:id => 1)
      end
    end

    def solve2
      quests=Quest.where(id: [6,7,8,9,10])

      if params[:id].to_i == 10
        @url = "/math/report2"
      else
        @url = "/math/solve2?id=#{params[:id].to_i + 1}"
      end
      @quest = Quest.find(params[:id])
      grade(params[:answer], @quest)
      render 'solve'
    end

    def solve
      # final_quest_id = session[:final_quest_id]
      # @final_quests = Quest.where(quest_id: final_quest_id)
      # session[:final_quest_id] = nil
      # answers.push(params[:answer]
      quests=Quest.all.limit(5)

      if params[:id].to_i == 5
        @url = "/math/report"
      else
        @url = "/math/solve?id=#{params[:id].to_i + 1}"
      end
      @quest = quests[params[:id].to_i-1]
      grade(params[:answer], @quest)
    end

    def explain
      @quest = Quest.find(params[:quest_id])
      @q_units = @quest.info.keys
      if params[:url] == "main"
        @url = :back
      else
        Uquest.create!(user_id: current_user.id, quest_id: params[:quest_id], correct: 0, cnt: current_user.cnt)
        if params[:id].to_i == 5
        @url = "/math/report"
        elsif params[:id].to_i == 10
          @url = "/math/report2"
        elsif current_user.cnt.even? && current_user.cnt!=0
          @url = "/math/solve2?id=#{params[:id].to_i + 1}"
        else
          @url = "/math/solve?id=#{params[:id].to_i + 1}"
        end
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to "/home/index" if user_signed_in?
  end

  def create
    log_in 1
    redirect_to "/home/index"
    # user = User.find_by(email: params[:email].downcase)
    # if user && user.authenticate(params[:password])
    #   log_in user
    #   redirect_to "/home/index"
    # else
    #   flash.now[:danger] = '잘못된 이메일과 비밀번호입니다.'
    # end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/math_helper.rb
module MathHelper
  def get_report(user,cnt,index)
    result= Hash.new
    first=Uquest.where(user_id: user.id,cnt: cnt)
    second= Hash.new
    Subject.find(3).units.each do |u|
      second[u.id]=0
    end
    Quest.where(id: Uquest.fail_ary(user,cnt)).select(:info).each do |q_unit|
      q_unit.info.keys.each do |key|
        second[key.to_i]+=q_unit.info[key].to_i*5
      end
    end
    result["1"]=first
    result["2"]=second #{unit: 점수,unit: 점수}
    return result[index.to_s]
  end

  def grade(answer_submit,answer_quest)
    if answer_submit.present?
      if answer_submit.to_i == answer_quest.answer
        Uquest.create!(user_id: current_user.id, quest_id: answer_quest.id-1, correct: 1, cnt: current_user.cnt)
      else
        Uquest.create!(user_id: current_user.id, quest_id: answer_quest.id-1, correct: 0, cnt: current_user.cnt)
      end
    end
  end

  def get_unit_name
    ary=[]
    Unit.all.each do |u|
      ary.push(u.name)
    end
    return ary
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #세션 생성
  def log_in(user)
    # session[:user_id] = user.id
    session[:user_id] = user
  end
  #현재 유저 확인
  def current_user
    @current_user = User.find_by(id: session[:user_id])
  end
  #유저가 로그인했는지?
  def user_signed_in?
    !current_user.nil?
  end
  def log_out
    session[:user_id] = 0
  end
end

app/views/home/index.html.erb
<a href="/math">
<div class="col-12 index_image">
    <img class="select_subject" src="<%=asset_path 'select_subject.png' %>"></img>
    <div class="char">
      <p>단원 선택</p>
    </div>
</div>
</a>
<div class="line col-12">
</div>
<a href="#">
<div class="col-12 index_image">
    <img class="report" src="<%=asset_path 'report.png' %>"></img>
    <div class="char">
      <p>분석 레포트</p>
    </div>
</div>
</a>
<!-- <%= current_user.name %>
<%= link_to("로그아웃",logout_path,method: :delete)%> -->

app/views/home/splash.html.erb
<div class="container">

  <div id="splash_bg">
  <div id="splash" class="splash" style="padding-top: 150px;">
      <!-- <div class="col-xs-4"><img class="" src="<%=asset_path '1.jpg' %>" style="max-width: 100%;"></img></div>
      <div class="col-xs-4"><img class="spinner_s" src="<%=asset_path 'pie.png'%>"style="max-width: 100%;"></img></div>
      <div class="col-xs-4"><img class="" src="<%=asset_path '2.jpg'%>"style="max-width: 100%;"></img></div> -->
      <img class="spinner_s" src="<%=asset_path 'inspiere.png'%>" width="100%"></img>
      <!--<h1 class="spinner_s1" >PRODUCE<br>LION</h1><br>-->
      <h3 id="fadein" style="margin-top: 100px;">대한민국 교육의 미래<br>와이</h1>
  </div>
</div>


<script type="text/javascript">
            $('#splash').ready()
            {
                $('#main').load('splash');
                setTimeout(function() {
                    $('#main').ready(function() {
                        $('#splash').remove();
                        window.location.href = "/login";
                    });
                }, 6000);
            };
</script>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mathwatch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
    <meta name="viewport" content="width=device-width, user-scalable=no">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/math/explain.html.erb
<div class="line col-12">
</div>
<div class="col-12 text-center">
  <h3 style="font-weight: bold;">출제 의도</h3>
</div>

<div class="line col-12">
</div>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>구성 요소</th>
        <th>난이도</th>
        <th>내 상태</th>
      </tr>
    </thead>
    <tbody>
      <% @q_units.each do |u| %>
        <tr>
          <td><%=Unit.find(u).name%></td>
          <td><%=@quest.info[u]%></td>
          <td><%=Ulevel.find_by(user_id: current_user.id,unit_id: u).level%></td>
        </tr>
      <% end%>
    </tbody>
  </table>
  <div class="panel panel-default" style="margin-top: 15px;">
    <div class="panel-heading">문제 해설</div>
    <div class="panel-body">
      <img src="<%=asset_path 'a_1.PNG' %>" style="max-width: 100%"></img>
    </div>
  </div>
  <div class="text-right">
    <% if @url == :back %>
      <%= link_to '돌아 가기', @url,class: "btn btn-default" %>
    <% elsif @url == "/math/report" %>
      <%= link_to '분석레포트 가기', @url,class: "btn btn-default" %>
    <% else %>
      <%= link_to '다음 문제 가기', @url,class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/math/report.erb
<!-- <div class="line col-12">
</div> -->
<div class="col-12 text-center">
  <h3 style="font-weight: bold;">문제 상세 분석</h3>
</div>
<div class="line col-12">
</div>
<div class="container">
  <div class="panel panel-info" style="margin-top:10px;">
    <div class="panel-heading">
      <h3 class="panel-title">분석레포트</h3>
    </div>
    <div class="panel-body">
      <div>
        <canvas id="canvas"></canvas>
      </div>
    </div>
  </div>

  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">채점표</h3>
    </div>
    <div class="panel-body">
      <div>
        <table border="1" class="table table-hover">
          <thead>
            <tr>
              <th class="text-center">문항</th>
              <th class="text-center">정답</th>
              <th class="text-center">해설</th>
            </tr>
          </thead>
          <tbody align="center">
            <% @fdata.each_with_index do |d,index|%>
            <tr>
              <td>
                <%= index+1%>
              </td>
              <td>
                <% if d.correct%>
                  <span class="glyphicon glyphicon-ok" aria-hidden="true" style="color:red;"></span>
                <% else %>
                  <span class="glyphicon glyphicon-remove" aria-hidden="true" style="color:red;"></span>
                <% end %>
              </td>
              <td>
                <a href="<%=math_explain_path(:id => d.quest_id, :quest_id => d.quest_id,url: :main)%>"><span class="glyphicon glyphicon-search" aria-hidden="true" style="color:red;"></span></a>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="text-right">
    <% if action_name=="report" %>
      <a class="btn btn-default" href="/math/select">오답분석문제</a>
    <% else %>
      <a class="btn btn-default" href="/home/index">메인페이지 가기</a>
    <% end %>
  </div>
</div>


</div>
<script type="text/javascript">
  var name_ary = <%= raw get_unit_name%>;
  // var name_ary = <%= @sdata.keys %>;
  var data_ary = <%= @sdata.values%>;
  var barChartData = {
  labels: name_ary.slice(0,10),
  datasets: [{
    fillColor: "rgba(0,60,100,1)",
    strokeColor: "black",
    data: data_ary.slice(0,10)
  }]
  }

  var index = 10;
  var ctx = document.getElementById("canvas").getContext("2d");
  var barChartDemo = new Chart(ctx).Bar(barChartData, {
    responsive: true,
    barValueSpacing: 2,
    scaleFontSize: 0
  });
  setInterval(function() {
    barChartDemo.removeData();
    barChartDemo.addData([data_ary[index]], name_ary[index]);
    if(index == <%=@sdata.values.length-1%>){
      index=0
    }else{
      index++;
    }
  }, 3000);
</script>
    <!-- <div>
        <canvas id="canvas"></canvas>
    </div>
    <script>
        var MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
        var config = {
            type: 'line',
            data: {
                labels: <%= raw get_unit_name%>,
                datasets: [{
                    label: "My First dataset",
                    backgroundColor: "#FFD966",
                    borderColor: "#FFD966",
                    data: <%= @sdata.values%>,
                    fill: false,
                }]
            },
            options: {
                responsive: true,
                title:{
                    display:true,
                    text:'Chart.js Line Chart'
                },
                tooltips: {
                    mode: 'index',
                    intersect: false,
                },
                hover: {
                    mode: 'nearest',
                    intersect: true
                },
                scales: {
                    xAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Month'
                        }
                    }],
                    yAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Value'
                        },
                        ticks: {
                            min: 0,
                            max: 5,
                            // forces step size to be 5 units
                            stepSize: 0.5
                        }
                    }]
                }
            }
        };
        window.onload = function() {
            var ctx = document.getElementById("canvas").getContext("2d");
            window.myLine = new Chart(ctx, config);
        };

    </script> -->

app/views/math/solve.html.erb
<div class="col-12 num">
  <div class="char col-2">
    <%= params[:id] + "번" %>
  </div>
  <div class="char col-4">
    <%= "2009년 수능 18번" %>
  </div>
</div>

<div class="line col-12">
</div>

<%= form_tag(@url, class: "form") do %>
    <div class="col-12 quest">
      <img class="quest_title" src="<%=asset_path @quest.title %>"></img>
    </div>

    <div class="answers">
      <ul>
          <% [1,2,3,4,5].each do |i| %>
              <li>
                <%= radio_button_tag 'answer', i %>
                <%= label_tag 'answer', "#{i}" + "번: 보기"%>
              </li>
          <% end %>
      </ul>
    </div>

    <div class="explain">
      <%= link_to "<img src=\"#{asset_path('button_back.png')}\" />".html_safe, :back, :class => "back_button"  %>
      <%= link_to math_explain_path(:id => params[:id].to_i, :quest_id => @quest.id), class: "button_explain" do %>
        <img class="quest_title" src="<%=asset_path 'button.png' %>"></img>
      <% end %>
      <%= submit_tag "", :type => :image, :src => asset_path("button_front") %>
      <!-- <img class="quest_title" src="<%=asset_path 'button_front.png' %>"></img> -->
    </div>
<% end %>

app/views/math/start.html.erb
<div class="col-12 header">
  <div class="char">
    <%= "단원선택" %>
  </div>
</div>
<div class="line col-12">
</div>

<%= form_tag(math_select_path) do %>
    <h2 style="text-align: center;">수학 Ⅱ</h2>
    <div class="line_start col-12">
    </div>
    <div class="ul_start">
      <% @subjects_su2.each do |subject| %>

          <%= check_box_tag 'subject_ids[]', subject.id, false, class: 'subject_input', id: "#{subject.id}" %>
          <%= label_tag "#{subject.id}", subject.name, class: "subject_text" %>

      <% end %>
    </div>
    <div class="line_start col-12">
    </div>
    <h2 style="text-align: center;">미적분 Ⅰ</h2>
    <div class="line_start col-12">
    </div>
    <ul class="ul_start">
      <% @subjects_der.each do |subject| %>
        <li class="li_start">
          <%= check_box_tag 'subject_ids[]', subject.id, false, class: 'subject_input', id: "#{subject.id}" %>
          <%= label_tag "#{subject.id}", subject.name, class: "subject_text" %>
        </li>
      <% end %>
    </ul>

    <div class="submit">
      <%= submit_tag "", :type => :image, :src => asset_path("button_subject") %>
    </div>
<% end %>